name: CI-CD

on:
  push:
    branches: ["master"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.12.0"

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Deploying to cloud
        run: echo "Deploying to cloud..."
